#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"


if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

cp "/tmp/ddwDome_X2/domelist ddwDome.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR//DomePlugIns/ddwDome.ui"
cp "/tmp/ddwDome_X2/ddwDome.ui" "$PLUGINS_DIR//DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR//DomePlugIns/libddwDome.dylib"
cp "/tmp/ddwDome_X2/libddwDome.dylib" "$PLUGINS_DIR//DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist ddwDome.txt"
	chown $app_owner "$PLUGINS_DIR//DomePlugIns/ddwDome.ui"
	chown $app_owner "$PLUGINS_DIR//DomePlugIns/libddwDome.dylib"
fi
chmod  755 "$PLUGINS_DIR//DomePlugIns/libddwDome.dylib"
rm -rf /tmp/ddwDome_X2

